export const questionnaireConstants = {
    CREATE_NEW_QUESTIONNAIRE: 'CREATE_NEW_QUESTIONNAIRE',
    CREATE_NEW_QUESTIONNAIRE_SUCCESS: 'CREATE_NEW_QUESTIONNAIRE_SUCCESS',
    CREATE_NEW_QUESTIONNAIRE_FAIL: 'CREATE_NEW_QUESTIONNAIRE_FAIL',
    LOAD_QUESTIONNAIRE: 'LOAD_QUESTIONNAIRE',
    LOAD_QUESTIONNAIRE_SUCCESS: 'LOAD_QUESTIONNAIRE_SUCCESS',
    LOAD_QUESTIONNAIRES_SUCCESS: 'LOAD_QUESTIONNAIRES_SUCCESS',
    LOAD_QUESTIONNAIRE_FAIL: 'LOAD_QUESTIONNAIRE_FAIL',
    LOAD_UNCOMPLETED_QUESTIONNAIRES: 'LOAD_UNCOMPLETED_QUESTIONNAIRES',
    LOAD_UNCOMPLETED_QUESTIONNAIRE: 'LOAD_UNCOMPLETED_QUESTIONNAIRE',
    UPDATE_QUESTIONNAIRE_SUCCESS: 'UPDATE_QUESTIONNAIRE_SUCCESS',
    DELETE_QUESTIONNAIRE_SUCCESS: 'DELETE_QUESTIONNAIRE_SUCCESS',
    SET_ACTIVE_PAGE: 'SET_ACTIVE_PAGE',
    UPDATE_QUESTIONNAIRE_PAGE_ANSWERS: 'UPDATE_QUESTIONNAIRE_ANSWERS',
    SUBMIT_ANSWERS_SUCCESS: 'SUBMIT_ANSWERS'
};

export const DEFAULT_QUESTIONNAIRE_TITLE = 'My new questionnaire';