export const questionnaireConstants = {
    CREATE_NEW_QUESTIONNAIRE: 'CREATE_NEW_QUESTIONNAIRE',
    CREATE_NEW_QUESTIONNAIRE_SUCCESS: 'CREATE_NEW_QUESTIONNAIRE_SUCCESS',
    CREATE_NEW_QUESTIONNAIRE_FAIL: 'CREATE_NEW_QUESTIONNAIRE_FAIL',
    LOAD_QUESTIONNAIRE: 'LOAD_QUESTIONNAIRE',
    LOAD_QUESTIONNAIRE_SUCCESS: 'LOAD_QUESTIONNAIRE_SUCCESS',
    LOAD_QUESTIONNAIRE_FAIL: 'LOAD_QUESTIONNAIRE_FAIL',
    EDIT_QUESTIONNAIRE: 'EDIT_QUESTIONNAIRE',
    DELETE_QUESTIONNAIRE: 'DELETE_QUESTIONNAIRE'
};

export const DEFAULT_QUESTIONNAIRE_TITLE = 'My new questionnaire';