export const questionConstants = {
    CREATE_NEW_QUESTION: 'CREATE_NEW_QUESTION',
    CREATE_NEW_QUESTION_SUCCESS: 'CREATE_NEW_QUESTION_SUCCESS',
    UPDATE_QUESTION_SUCCESS: 'UPDATE_QUESTION_SUCCESS',
    LOAD_QUESTION: 'LOAD_QUESTION',
    DELETE_QUESTION_SUCCESS: 'DELETE_QUESTION_SUCCESS',
    CLEAR_QUESTION: 'CLEAR_QUESTION'
};

export const questionType = {
  TEXT: "TEXT",
  MULTIPLE_CHOICE: "MULTIPLE_CHOICE",
  SINGLE_CHOICE: "SINGLE_CHOICE",
};

export const questionTypeReadable = {
    TEXT: 'Text',
    YES_NO: 'Yes - no',
    MULTIPLE_CHOICE: 'Multiple choice',
    SINGLE_CHOICE: 'Single choice'
};
